version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 5.0
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password | docker login --username AWS --password-stdin $REPOSITORY_URI
      - IMAGE_URI="${REPOSITORY_URI}:latest"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --tag "$IMAGE_URI" .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Push the latest Docker Image...
      - docker push "$IMAGE_URI"
      - printf '[{"name":"user-bff","imageUri":"%s"}]' "$IMAGE_URI" > images.json
artifacts:
  files:
    - buildspec.yml
    - images.json